# Install pre-commit hooks via:
# pre-commit install
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: double-quote-string-fixer
      exclude: &exclude_files >
        (?x)^(
            tests/data/.*
        )$
    - id: end-of-file-fixer
      exclude: *exclude_files
    - id: fix-encoding-pragma
      exclude: *exclude_files
    - id: mixed-line-ending
      exclude: *exclude_files
    - id: trailing-whitespace
      exclude: *exclude_files
    - id: check-json
      exclude: *exclude_files

# yapf = yet another python formatter
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0
  hooks:
  - id: yapf
    name: yapf
    args: ["-i"]
    exclude: *exclude_files

- repo: local
  hooks:
  - id: pylint
    language: system
    types: [file, python]
    name: pylint
    description: "This hook runs the pylint static code analyzer"
    exclude: >
      (?x)^(
          tests/data.*|
          docs/.*|
      )$
    entry: pylint

  - id: version-number
    name: Check version numbers
    entry: python ./.github/check_version.py
    language: system
    files: '^(setup.json)|(aiida_psi4/__init__.py)'
