[tool.pylint.format]
max-line-length = 125

[tool.pylint.messages_control]
disable = [
    "too-many-ancestors",
    "invalid-name",
]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:aiida:",
    "ignore::DeprecationWarning:plumpy:",
    "ignore::DeprecationWarning:django:",
    "ignore::DeprecationWarning:yaml:",
]

addopts = "--durations=0 --cov=aiida_psi4"
testpaths = [
    "tests",
    "examples",
]
# test also examples
python_files = "test_*.py example_*.py"
